[[ -f ~/.bashrc ]] && . ~/.bashrc
if [ ! -d ~/.sessions ]; then
  mkdir -p ~/.sessions;
fi
touch ~/.sessions/$BASHPID

bash cluster start

exit_session() {
    . "$HOME/.bash_logout"
}
trap exit_session SIGHUP