#!/bin/bash
set -e
if [[ $(bash check-cluster) == "Cluster does not exist" ]]; then 
    k3d cluster create --config /etc/k3dconfig.yml
    if [[ -n "${DEV}" ]]; then 
        # if in dev mode, replace to localhost
        sed -i -E "s/server:(.*):\d+/server: https:\/\/k3d-$USERNAME-serverlb:6443/g" ~/.kube/config
    else
        # otherwise, rewrite to use port 6443
        sed -i -E 's/server:(.*):\d+/server: \1:6443/g' ~/.kube/config 
    fi
    echo "Cluster has been created!"
fi